# Generated by Django 4.2.4 on 2023-08-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
    ]
