# Generated by Django 4.2.1 on 2023-07-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_salesitems_tcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesitems',
            name='tcost',
            field=models.FloatField(default=0, null=True),
        ),
    ]
