# Generated by Django 4.2.4 on 2023-08-23 09:16

from django.db import migrations, models
import django.utils.timezone
import posApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_remove_position_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department_name',
            field=models.TextField(default=django.utils.timezone.now, verbose_name=posApp.models.Department),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='position_name',
            field=models.ManyToManyField(to='posApp.position'),
        ),
    ]
