# Generated by Django 4.2.4 on 2023-08-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_alter_employee_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='position_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
