# Generated by Django 4.2.1 on 2023-07-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_rename_user_employee_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user_id',
            new_name='user',
        ),
    ]
