# Generated by Django 4.2.1 on 2023-07-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_rename_user_id_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
