# Generated by Django 4.2.4 on 2023-09-02 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_alter_damages_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damages',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.products'),
        ),
    ]
