# Generated by Django 4.2.4 on 2023-09-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_alter_damages_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damages',
            old_name='product_id',
            new_name='product',
        ),
    ]
