# Generated by Django 4.2.4 on 2023-09-02 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_rename_product_id_damages_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damages',
            old_name='product',
            new_name='product_id',
        ),
    ]
