# Generated by Django 4.2.4 on 2023-09-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_rename_product_damages_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='damages',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
