# Generated by Django 4.2.4 on 2023-09-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_damages_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/damaged_product_images/'),
        ),
    ]
