# Generated by Django 4.2.4 on 2023-09-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_alter_damages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageBulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='Damages')),
            ],
        ),
    ]
